/**
 * Jev (TypeSafe) — reference data for /typesafe-jev.
 *
 * Same two-surface rule as lib/union-alpha.ts: `verifiedSpecs` is re-checkable
 * against a public listing, `claims` is other people's reporting with the
 * evidence attached. The two never share a table.
 *
 * Every number here was read on 2026-09-18 from one of three primary sources:
 *   - https://openrouter.ai/api/v1/models/typesafe/jev-1.13/endpoints
 *   - https://developers.cloudflare.com/ai/models/typesafe/jev/
 *   - https://typesafe.ai/blog/introducing-system-one-models-and-jev
 * Nothing on this page is taken from a social post.
 *
 * Note on the catalogue: `typesafe/jev-1.13` answers on the single-model
 * endpoint and is served, but it is **not** in the `/api/v1/models` list our
 * sync reads, so this page cannot be generated by `sync-openrouter-models` —
 * it is hand-maintained on purpose. That is recorded in the timeline rather
 * than hidden, because it is the reason the numbers need a date.
 */

export const JEV_DATA_AS_OF = "2026-09-18";
export const JEV_MODEL_ID = "typesafe/jev-1.13";
export const JEV_OPENROUTER_URL = "https://openrouter.ai/typesafe/jev-1.13";
export const JEV_CLOUDFLARE_URL = "https://developers.cloudflare.com/ai/models/typesafe/jev/";
export const JEV_TYPESAFE_BLOG_URL = "https://typesafe.ai/blog/introducing-system-one-models-and-jev";

/** Unix 1789689684, read from the catalogue's `created` field. */
export const JEV_LISTED_AT_UTC = "2026-09-18T00:01:24Z";

export const JEV_INPUT_PRICE_PER_MILLION = 0.042;

export interface VerifiedSpec {
  label: string;
  value: string;
  note?: string;
}

export const verifiedSpecs: VerifiedSpec[] = [
  {
    label: "OpenRouter ID",
    value: JEV_MODEL_ID,
    note: "Display name in the picker is “TypeSafe: Jev 1.13”.",
  },
  {
    label: "Maker",
    value: "TypeSafe AI",
    note: "Announced by the founder, Diogo Almeida, on the TypeSafe blog on 2026-09-15.",
  },
  {
    label: "Class",
    value: "System One model",
    note: "TypeSafe’s own category: models built to return decisions rather than prose.",
  },
  {
    label: "Input / output",
    value: "Text (program state) in → typed decisions out",
    note: "The catalogue field reads `text->decisions`. It is not a chat endpoint.",
  },
  {
    label: "Context window",
    value: "32,000 tokens",
    note: "Read from the OpenRouter endpoint and the Cloudflare Workers AI model card; both agree.",
  },
  {
    label: "Price — input",
    value: `$${JEV_INPUT_PRICE_PER_MILLION} per million tokens`,
    note: "$0.000000042 per token. The vendor quotes the same figure as $42 per billion tokens.",
  },
  {
    label: "Price — output",
    value: "Free",
    note: 'The catalogue lists completion price 0, and the vendor says "output tokens: FREE (too cheap to meter)".',
  },
  {
    label: "Serving provider",
    value: "TypeSafe",
    note: "Single endpoint, provider tag TypeSafe — the maker serves it directly.",
  },
  {
    label: "Question types",
    value: "Noul, Choice, Score",
    note: "Noul is the yes/no form (criteria you name, answered as a probability); Choice picks from a named set; Score grades on an ordered scale.",
  },
  {
    label: "Every answer carries",
    value: "A probability and a confidence",
    note: "Cloudflare’s model card: “returns calibrated answers with probabilities and confidence”.",
  },
  {
    label: "Training method",
    value: "RLCD — Reinforcement Learning for Calibrated Decisions",
    note: "The vendor’s name for the method; the alternative they describe it against is RLHF/RLVR.",
  },
  {
    label: "Vendor speed claim",
    value: "70 ms – 500 ms end to end",
    note: "Against “3 to 329 seconds for frontier models”, which the vendor frames as 40×–200× faster on System One shaped queries. Their own number, not an independent benchmark.",
  },
  {
    label: "Availability",
    value: "Early access — waitlist",
    note: "The 2026-09-15 announcement calls Jev “available today in early access”; TypeSafe’s site carries a Join Waitlist link.",
  },
  {
    label: "Also listed on",
    value: "Cloudflare Workers AI",
    note: `Model id \`typesafe/jev\`, described there as a third-party model. ${JEV_CLOUDFLARE_URL}`,
  },
];

export interface TimelineEntry {
  date: string;
  title: string;
  detail: string;
}

export const timeline: TimelineEntry[] = [
  {
    date: "2026-09-15",
    title: "TypeSafe announces System One models and Jev",
    detail:
      "Diogo Almeida, founder, publishes the launch post: two years in stealth, a new architecture with a parallel sampler, and RLCD as the training method. Jev ships in early access with a waitlist.",
  },
  {
    date: "2026-09-15 → 16",
    title: "Search interest leaves the floor",
    detail:
      "Worldwide Google Trends index for “jev” had sat flat for three months. It moves 1 → 4 on 15 September and 4 → 26 on 16 September — the first time the term has moved at all in the window.",
  },
  {
    date: "2026-09-17",
    title: "Interest doubles again, and the AI reading wins",
    detail:
      "Index 26 → 61. The related queries that appear are all AI-side: “ai jev”, “jev typesafe”, “jev model ai”, “typesafe ai”, “llm jev”, “diogo almeida”.",
  },
  {
    date: "2026-09-18 00:01 UTC",
    title: "Jev is listed on OpenRouter",
    detail:
      `The catalogue returns \`${JEV_MODEL_ID}\` with a creation time of ${JEV_LISTED_AT_UTC}, 32,000 context and input at $${JEV_INPUT_PRICE_PER_MILLION} per million tokens with free output. “openrouter jev” becomes a breakout rising query the same day.`,
  },
  {
    date: "2026-09-18",
    title: "The term peaks, and the reference pages land",
    detail:
      "Index reaches 100 — the high point of the trailing three months, up from a floor of 1. Cloudflare’s Workers AI model card and a LangChain harness guide both go up the same day.",
  },
];

export interface CommunityClaim {
  claim: string;
  evidence: string;
  confidence: "Medium" | "Low";
}

export const claims: CommunityClaim[] = [
  {
    claim: "“Up to 190× faster and 440× cheaper than an LLM.”",
    evidence:
      "This circulates on X as a summary of the vendor’s own figures. The arithmetic follows from the published ranges (70 ms vs 3 s, $0.042 in / $0 out vs $0.20–$10 in), but the baseline is the vendor’s, chosen to compare a decision call against a chat call. Treat it as the vendor’s comparison restated, not as an independent benchmark.",
    confidence: "Medium",
  },
  {
    claim: "People are using Jev to drive website operations and automated trading.",
    evidence:
      "Reported in the X timeline on 2026-09-18, in threads that are hours old. We found no published workflow, repo or result that we could check, and no returns claim can be verified at all. Directional chatter about a three-day-old model, nothing more.",
    confidence: "Low",
  },
  {
    claim: "Jev is the start of a split in how AI gets used, not another chatbot.",
    evidence:
      "The most-shared take on X and LinkedIn on 18 September, arguing that decision models will absorb the automation work LLMs were being asked to do. It is an argument, not a measurement — but it is the reason the term is being searched, so it is worth knowing it exists.",
    confidence: "Low",
  },
];

export interface DisambiguationRow {
  name: string;
  what: string;
}

/**
 * The bare string "jev" is genuinely shared. This block exists so a reader who
 * landed here looking for one of the others can tell in one glance, and so the
 * page never pretends the term is uncontested.
 */
export const alsoCalledJev: DisambiguationRow[] = [
  {
    name: "jev.",
    what:
      "Jephté Kewto, a Congolese-Canadian rapper — Wikipedia entry, ~1.6M monthly listeners on Spotify. The largest legitimate non-AI meaning.",
  },
  {
    name: "FaZe Jev",
    what: "A YouTube channel with millions of followers. “faze jev” is the second-largest related query for the term.",
  },
  {
    name: "JEV",
    what:
      "Japanese encephalitis virus. “jev vaccine”, “jev symptoms” and “jev virus” are the medical cluster, served by WHO/CDC-grade pages.",
  },
  {
    name: "jev (Czech/Slovak)",
    what:
      'An ordinary word meaning “phenomenon” — “meteorologický jev”, meteorological phenomenon, is a standing Czech search. A reminder that the three-letter string has a life of its own outside English.',
  },
];

export interface FaqItem {
  question: string;
  answer: string;
}

export const jevFaqs: FaqItem[] = [
  {
    question: "What is Jev?",
    answer:
      "Jev is a model from TypeSafe AI, announced on 2026-09-15. Instead of generating text it takes program state in and returns typed decisions out — a yes/no with a probability, a choice from a set you define, or a score on a scale you define. TypeSafe calls this class a System One model.",
  },
  {
    question: "Is Jev on OpenRouter?",
    answer:
      `Yes. The catalogue serves \`${JEV_MODEL_ID}\` — 32,000 context, $${JEV_INPUT_PRICE_PER_MILLION} per million input tokens, output free — and the model page is at ${JEV_OPENROUTER_URL}. One caveat worth knowing: it answers on its own endpoint but is not returned by the \`/api/v1/models\` list, so tools that build off that list will not see it.`,
  },
  {
    question: "Is Jev an LLM? Can it write text or code?",
    answer:
      "No. It gives up string generation entirely — that is the trade the vendor made for speed and for never producing a type error. If you need prose, code or a chat answer, Jev is the wrong tool; it is built to be called by code that already knows what it is going to do with the answer.",
  },
  {
    question: "What is a System One model?",
    answer:
      "TypeSafe’s term for a model trained to make fast, structured decisions rather than to produce human-pleasing text. The vendor’s framing is a function call with frontier intelligence behind it: unstructured state in, typed probabilistic decisions out. The training method is named RLCD — Reinforcement Learning for Calibrated Decisions.",
  },
  {
    question: "What do Noul, Choice and Score mean?",
    answer:
      "They are the three question types. Noul is the boolean form — you name the true and false criteria and get back a probability between 0 and 1. Choice asks the model to pick one option from a set you define. Score asks it to place the answer on an ordered scale you define. Every answer comes with a probability and a confidence.",
  },
  {
    question: "How much does Jev cost?",
    answer:
      `$${JEV_INPUT_PRICE_PER_MILLION} per million input tokens on OpenRouter — the vendor quotes the same as $42 per billion — and output is free. Read the input figure as the whole bill: the model returns a decision, not a body of text, so there is no large completion to pay for.`,
  },
  {
    question: "How fast is Jev?",
    answer:
      "The vendor claims 70 ms to 500 ms end to end, against 3 to 329 seconds for frontier LLMs, and describes that as 40× to 200× faster on System One shaped queries. That is the maker’s measurement, run from their own machines; we have not reproduced it.",
  },
  {
    question: "Is Jev free?",
    answer:
      "Output is free and input is $0.042 per million tokens, which is close to free in practice — a million decisions costs about four cents of input. It is not a free-preview model though: this is the listed price, not a temporary window like the Alpha-line stealth releases had.",
  },
  {
    question: "Can I run Jev on Cloudflare Workers AI?",
    answer:
      "Yes — it is listed in the Cloudflare Workers AI catalogue as the third-party model `typesafe/jev`, with a code sample that calls it through `env.AI.run` and passes state plus a questions object. Same model, different front door from OpenRouter.",
  },
  {
    question: "Is this the same Jev as FaZe Jev, the rapper jev., or the JEV virus?",
    answer:
      "No. All four share three letters and nothing else. Those other meanings have far more search volume than the model does — which is exactly why this page names them instead of quietly counting their traffic as ours.",
  },
  {
    question: "Can Jev be used for automated trading?",
    answer:
      "It is being discussed that way on X, and a model that returns calibrated probabilities in under a second is a plausible fit for decision points in a trading loop. But we could not find a single published, checkable result — and nobody publishes a verified returns claim. Treat it as a rumour about a three-day-old model. This page will say so until there is something to link to.",
  },
];
